// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/applications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-applications"
                ],
                "summary": "Список всех заявок (admin)",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "new",
                                "in_review",
                                "printing",
                                "ready",
                                "issued",
                                "rejected",
                                "cancelled"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Фильтр по статусам",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по имени / email",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID материала",
                        "name": "material_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Дата создания от (YYYY-MM-DD)",
                        "name": "created_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Дата создания до (YYYY-MM-DD)",
                        "name": "created_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Желаемая дата от (YYYY-MM-DD)",
                        "name": "desired_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Желаемая дата до (YYYY-MM-DD)",
                        "name": "desired_to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Страница",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "type": "integer",
                        "default": 20,
                        "description": "Записей на странице",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.AdminApplicationListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/applications/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-applications"
                ],
                "summary": "Детали заявки (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ApplicationDetailAdmin"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/applications/{id}/files/{file_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-applications"
                ],
                "summary": "Скачать файл заявки (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID файла",
                        "name": "file_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Файл удалён",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/applications/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-applications"
                ],
                "summary": "Изменить статус заявки (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ChangeStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ChangeStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный статус / отсутствует обязательное поле",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Заявка в финальном статусе",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/materials": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-materials"
                ],
                "summary": "Все материалы (admin)",
                "responses": {
                    "200": {
                        "description": "items",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.MaterialResponse"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-materials"
                ],
                "summary": "Создать материал (admin)",
                "parameters": [
                    {
                        "description": "Данные материала",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.CreateMaterialRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.MaterialResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Материал с таким названием уже существует",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/materials/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-materials"
                ],
                "summary": "Обновить материал (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID материала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Изменяемые поля",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.PatchMaterialRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.MaterialResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Название уже занято",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/materials/{id}/colors": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-materials"
                ],
                "summary": "Добавить цвет к материалу (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID материала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные цвета",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.CreateColorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ColorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Цвет с таким названием уже существует",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/materials/{id}/colors/{color_id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-materials"
                ],
                "summary": "Обновить цвет (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID материала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID цвета",
                        "name": "color_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Изменяемые поля",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.PatchColorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ColorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Название уже занято",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-stats"
                ],
                "summary": "Статистика (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Начало периода (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Конец периода (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.StatsResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный период",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Поиск пользователей по email (admin)",
                "parameters": [
                    {
                        "minLength": 3,
                        "type": "string",
                        "description": "Минимум 3 символа",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.AdminUsersResponse"
                        }
                    },
                    "400": {
                        "description": "Запрос слишком короткий",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/users/{id}/role": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Изменить роль пользователя (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новая роль",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.SetRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.SetRoleResponse"
                        }
                    },
                    "400": {
                        "description": "Недопустимое значение роли",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Нельзя снять роль с последнего администратора",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/applications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Список заявок пользователя",
                "parameters": [
                    {
                        "enum": [
                            "new",
                            "in_review",
                            "printing",
                            "ready",
                            "issued",
                            "rejected",
                            "cancelled"
                        ],
                        "type": "string",
                        "description": "Фильтр по статусу",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Страница",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "type": "integer",
                        "default": 20,
                        "description": "Записей на странице",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ApplicationListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется согласие",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Создать заявку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Должность / группа заявителя",
                        "name": "position",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Цель печати",
                        "name": "purpose",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID материала",
                        "name": "material_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Важен ли цвет",
                        "name": "color_matters",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID цвета (обязателен если color_matters=true)",
                        "name": "color_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Желаемая дата получения (YYYY-MM-DD)",
                        "name": "desired_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Комментарий",
                        "name": "comment",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Файлы моделей (STL / STEP / 3MF, до 20 МБ каждый)",
                        "name": "files[]",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.CreateApplicationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется согласие",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Профиль не заполнен / лимит заявок / материал недоступен",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Файл слишком большой",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/applications/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Получить заявку",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ApplicationDetailUser"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется согласие",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/applications/{id}/cancel": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Отменить заявку",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.CancelApplicationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется согласие",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Отмена невозможна",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/applications/{id}/files": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Добавить файл к заявке",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Файл модели (STL / STEP / 3MF, до 20 МБ)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.UploadFileResponse"
                        }
                    },
                    "400": {
                        "description": "Файл не передан или неверный формат",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется согласие",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Заявка не в статусе new",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Файл слишком большой",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/applications/{id}/files/{file_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Скачать файл (редирект на presigned URL)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID файла",
                        "name": "file_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется согласие",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Файл удалён",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выйти (отозвать refresh token)",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновить токены",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.RefreshResponse"
                        }
                    },
                    "401": {
                        "description": "Невалидный/просроченный/отозванный token",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/request-otp": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Запросить OTP-код",
                "parameters": [
                    {
                        "description": "Email адрес",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.RequestOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.RequestOTPResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Превышен лимит запросов",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/verify-otp": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Подтвердить OTP-код",
                "parameters": [
                    {
                        "description": "Email + OTP-код",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.VerifyOTPResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный или истёкший код",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "OTP не найден",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "423": {
                        "description": "Слишком много попыток",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/materials": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "materials"
                ],
                "summary": "Список доступных материалов",
                "responses": {
                    "200": {
                        "description": "items",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.MaterialResponse"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется согласие",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Получить профиль",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Профиль не найден",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Обновить профиль",
                "parameters": [
                    {
                        "description": "Изменяемые поля",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.PatchProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Требуется согласие",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/profile/consent": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Дать согласие на обработку данных",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ConsentResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "miem_3d_lab_print_backend_src_internal_apierr.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INTERNAL_ERROR"
                },
                "details": {
                    "type": "object"
                },
                "message": {
                    "type": "string",
                    "example": "Внутренняя ошибка сервера"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_apierr.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_apierr.APIError"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.AdminApplicant": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "string"
                },
                "snapshot_email": {
                    "type": "string"
                },
                "snapshot_full_name": {
                    "type": "string"
                },
                "telegram": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.AdminApplicationListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deadline_soon": {
                    "type": "boolean"
                },
                "desired_date": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "material_name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.AdminApplicationListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.AdminApplicationListItem"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.PaginationMeta"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.AdminUserItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.AdminUsersResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.AdminUserItem"
                    }
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ApplicationDetailAdmin": {
            "type": "object",
            "properties": {
                "applicant": {
                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.AdminApplicant"
                },
                "color": {
                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ColorRef"
                },
                "color_matters": {
                    "type": "boolean"
                },
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "desired_date": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.FileItem"
                    }
                },
                "id": {
                    "type": "string"
                },
                "material": {
                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.MaterialRefAdmin"
                },
                "number": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "rejection_reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.StatusHistoryItemAdmin"
                    }
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ApplicationDetailUser": {
            "type": "object",
            "properties": {
                "color": {
                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ColorRef"
                },
                "color_matters": {
                    "type": "boolean"
                },
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "desired_date": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.FileItem"
                    }
                },
                "files_delete_after": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "material": {
                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.MaterialRef"
                },
                "number": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "rejection_reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.StatusHistoryItemUser"
                    }
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ApplicationListItem": {
            "type": "object",
            "properties": {
                "color_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "desired_date": {
                    "type": "string"
                },
                "files_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "material_name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ApplicationListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ApplicationListItem"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.PaginationMeta"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ByMaterialStat": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "material_name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.CancelApplicationResponse": {
            "type": "object",
            "properties": {
                "files_delete_after": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ChangeStatusRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "rejection_reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ChangeStatusResponse": {
            "type": "object",
            "properties": {
                "files_delete_after": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ColorRef": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "snapshot_name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ColorResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ConsentResponse": {
            "type": "object",
            "properties": {
                "consent_date": {
                    "type": "string"
                },
                "consent_given": {
                    "type": "boolean"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.CreateApplicationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.CreateColorRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.CreateMaterialRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.FileItem": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.MaterialRef": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "snapshot_name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.MaterialRefAdmin": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_active_now": {
                    "type": "boolean"
                },
                "snapshot_name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.MaterialResponse": {
            "type": "object",
            "properties": {
                "colors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ColorResponse"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.PaginationMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.PatchColorRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.PatchMaterialRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.PatchProfileRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "max": {
                    "type": "string"
                },
                "telegram": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.ProfileResponse": {
            "type": "object",
            "properties": {
                "consent_date": {
                    "type": "string"
                },
                "consent_given": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "max": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "telegram": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.RefreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.RequestOTPRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.RequestOTPResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.SetRoleRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.SetRoleResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.StatsResponse": {
            "type": "object",
            "properties": {
                "avg_completion_hours": {
                    "type": "number"
                },
                "by_material": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.ByMaterialStat"
                    }
                },
                "by_status_current": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "completed_count": {
                    "type": "integer"
                },
                "period": {
                    "type": "object",
                    "properties": {
                        "date_from": {
                            "type": "string"
                        },
                        "date_to": {
                            "type": "string"
                        }
                    }
                },
                "total_applications": {
                    "type": "integer"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.StatusHistoryChangedBy": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.StatusHistoryItemAdmin": {
            "type": "object",
            "properties": {
                "changed_by": {
                    "$ref": "#/definitions/miem_3d_lab_print_backend_src_internal_dto.StatusHistoryChangedBy"
                },
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.StatusHistoryItemUser": {
            "type": "object",
            "properties": {
                "changed_by_role": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.UploadFileResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.VerifyOTPRequest": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "miem_3d_lab_print_backend_src_internal_dto.VerifyOTPResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "consent_required": {
                    "type": "boolean"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите \"Bearer \u003caccess_token\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MIEM 3D Lab Print API",
	Description:      "REST API сервиса подачи заявок на 3D-печать МИЭМ НИУ ВШЭ.\\nАутентификация — OTP через email + JWT (Bearer token).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
